jQuery(document).ready(function(){
    var scripts = document.getElementsByTagName("script");
    var jsFolder = "";
    for (var i= 0; i< scripts.length; i++)
    {
        if( scripts[i].src && scripts[i].src.match(/initslider-1\.js/i))
            jsFolder = scripts[i].src.substr(0, scripts[i].src.lastIndexOf("/") + 1);
    }
    jQuery("#amazingslider-1").amazingslider({
        jsfolder:jsFolder,
        width: 478,
        height: 300,
        loadimageondemand: false,
        isresponsive: true,
        autoplayvideo: false,
        pauseonmouseover: false,
        randomplay: false,
        slideinterval: 5000,
        transitiononfirstslide: false,
        loop: 0,
        autoplay: true,
        navplayvideoimage: "play-32-32-0.png",
        navpreviewheight: 60,
        timerheight: 2,
        skin: "Events",
        textautohide: false,
        addgooglefonts: false,
        navshowplaypause: true,
        navshowplayvideo: false,
        navbuttonradius: 0,
        navpreviewposition: "top",
        navradius: 0,
        showshadow: false,
        navfeaturedarrowimagewidth: 16,
        navpreviewwidth: 120,
        googlefonts: "Inder",
        textpositionmarginright: 24,
        bordercolor: "",
        navthumbnavigationarrowimagewidth: 32,
        navthumbtitlehovercss: "text-decoration:none;",
        arrowwidth: 32,
        navmargin: 16,
        texteffecteasing: "easeOutCubic",
        texteffect: "slide",
        navspacing: 8,
        navarrowimage: "navarrows-28-28-0.png",
        ribbonimage: "ribbon_topright-0.png",
        navwidth: 155,
        navheight: 80,
        timeropacity: 0.6,
        navthumbnavigationarrowimage: "carouselarrows-32-32-0.png",
        navpreviewbordercolor: "#ffffff",
        ribbonposition: "topright",
        navthumbdescriptioncss: "display:block;position:relative;padding:2px 4px;text-align:left;font:normal 12px Arial,Helvetica,sans-serif;color:#333;",
        arrowstyle: "mouseover",
        navthumbtitleheight: 47,
        textpositionmargintop: 24,
        navswitchonmouseover: false,
        playvideoimage: "playvideo-64-64-0.png",
        arrowimage: "arrows-32-32-0.png",
        textstyle: "static",
        playvideoimageheight: 64,
        navfonthighlightcolor: "#666666",
        showbackgroundimage: false,
        navpreviewborder: 4,
        navdirection: "horizontal",
        navbuttonshowbgimage: true,
        navbuttonbgimage: "navbuttonbgimage-28-28-0.png",
        navthumbnavigationarrowimageheight: 32,
        textbgcss: "display:block; position:absolute; top:0px; left:0px; width:100%; height:100%; background-color:#333333; opacity:0.6; filter:alpha(opacity=60);",
        shadowcolor: "#aaaaaa",
        navborder: 0,
        bottomshadowimagewidth: 110,
        showtimer: false,
        navshowpreview: false,
        navpreviewarrowheight: 8,
        navfeaturedarrowimage: "featuredarrow-16-8-0.png",
        showribbon: false,
        navfeaturedarrowimageheight: 8,
        navstyle: "thumbnails",
        textpositionmarginleft: 24,
        descriptioncss: "display:block; position:relative; margin-top:4px; font:12px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#fff;",
        navplaypauseimage: "navplaypause-28-28-0.png",
        backgroundimagetop: -10,
        timercolor: "#ffffff",
        navfontsize: 12,
        navhighlightcolor: "#333333",
        navimage: "bullet-24-24-5.png",
        navbuttoncolor: "#999999",
        navshowarrow: true,
        navshowfeaturedarrow: true,
        titlecss: "display:block; position:relative; font: 14px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#fff;",
        ribbonimagey: 0,
        ribbonimagex: 0,
        shadowsize: 5,
        arrowhideonmouseleave: 1000,
        navopacity: 0.8,
        backgroundimagewidth: 120,
        navcolor: "#999999",
        navthumbtitlewidth: 120,
        playvideoimagewidth: 64,
        arrowheight: 32,
        arrowmargin: 8,
        texteffectduration: 1000,
        bottomshadowimage: "bottomshadow-110-95-4.png",
        border: 0,
        timerposition: "bottom",
        navfontcolor: "#333333",
        navthumbnavigationstyle: "auto",
        borderradius: 0,
        navbuttonhighlightcolor: "#333333",
        textpositionstatic: "bottom",
        navthumbstyle: "imageandtitle",
        textcss: "display:block; padding:12px; text-align:left;",
        navbordercolor: "",
        navpreviewarrowimage: "previewarrow-16-8-0.png",
        showbottomshadow: false,
        backgroundimage: "",
        navposition: "bottom",
        navpreviewarrowwidth: 16,
        bottomshadowimagetop: 95,
        textpositiondynamic: "bottomleft",
        navshowbuttons: false,
        navthumbtitlecss: "display:block;position:relative;padding:2px 4px;text-align:center;font:bold 11px Arial,Helvetica,sans-serif;color:#333;",
        textpositionmarginbottom: 24,
        slice: {
            duration: 1500,
            easing: "easeOutCubic",
            checked: true,
            effects: "up,down,updown",
            slicecount: 10
        },
        transition: "slice"
       /* width:478,
        height:300,
        loadimageondemand:false,
        isresponsive:true,
        autoplayvideo:false,
        pauseonmouseover:false,
        randomplay:false,
        slideinterval:5000,
        transitiononfirstslide:false,
        loop:0,
        autoplay:true,
        navplayvideoimage:"play-32-32-0.png",
        navpreviewheight:60,
        timerheight:2,
        skin:"Events",
        textautohide:false,
        addgooglefonts:false,
        navshowplaypause:true,
        navshowplayvideo:false,
        navbuttonradius:0,
        navpreviewposition:"top",
        navradius:0,
        showshadow:false,
        navfeaturedarrowimagewidth:16,
        navpreviewwidth:120,
        googlefonts:"Inder",
        textpositionmarginright:24,
        bordercolor:"",
        navthumbnavigationarrowimagewidth:32,
        navthumbtitlehovercss:"text-decoration:none;",
        arrowwidth:32,
        navmargin:20,
        texteffecteasing:"easeOutCubic",
        texteffect:"slide",
        navspacing:8,
        navarrowimage:"navarrows-28-28-0.png",
        ribbonimage:"ribbon_topleft-0.png",
        navwidth:155,
        navheight:80,
        timeropacity:0.6,
        navthumbnavigationarrowimage:"carouselarrows-32-32-0.png",
        navpreviewbordercolor:"#ffffff",
        ribbonposition:"topleft",
        navthumbdescriptioncss:"display:block;position:relative;padding:2px 4px;text-align:left;font:normal 12px Arial,Helvetica,sans-serif;color:#333;",
        arrowstyle:"mouseover",
        navthumbtitleheight:45,
        textpositionmargintop:24,
        navswitchonmouseover:false,
        playvideoimage:"playvideo-64-64-0.png",
        arrowimage:"arrows-32-32-0.png",
        textstyle:"static",
        playvideoimageheight:64,
        navfonthighlightcolor:"#666666",
        showbackgroundimage:false,
        navpreviewborder:4,
        navdirection:"horizontal",
        navbuttonshowbgimage:true,
        navbuttonbgimage:"navbuttonbgimage-28-28-0.png",
        navthumbnavigationarrowimageheight:32,
        textbgcss:"display:block; position:absolute; top:0px; left:0px; width:100%; height:100%; background-color:#333333; opacity:0.6; filter:alpha(opacity=60);",
        shadowcolor:"#aaaaaa",
        navborder:0,
        bottomshadowimagewidth:110,
        showtimer:true,
        navshowpreview:false,
        navpreviewarrowheight:8,
        navfeaturedarrowimage:"featuredarrow-16-8-0.png",
        showribbon:false,
        navfeaturedarrowimageheight:8,
        navstyle:"thumbnails",
        textpositionmarginleft:24,
        descriptioncss:"display:block; position:relative; margin-top:4px; font:12px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#fff;",
        navplaypauseimage:"navplaypause-28-28-0.png",
        backgroundimagetop:-10,
        timercolor:"#ffffff",
        navfontsize:12,
        navhighlightcolor:"#333333",
        navimage:"bullet-24-24-5.png",
        navbuttoncolor:"#999999",
        navshowarrow:true,
        navshowfeaturedarrow:true,
        titlecss:"display:block; position:relative; font: 14px Inder,Arial,Tahoma,Helvetica,sans-serif; color:#fff;",
        ribbonimagey:0,
        ribbonimagex:0,
        shadowsize:5,
        arrowhideonmouseleave:1000,
        navopacity:0.9,
        backgroundimagewidth:120,
        navcolor:"#999999",
        navthumbtitlewidth:120,
        playvideoimagewidth:64,
        arrowheight:32,
        arrowmargin:8,
        texteffectduration:1000,
        bottomshadowimage:"bottomshadow-110-95-4.png",
        border:0,
        timerposition:"bottom",
        navfontcolor:"#333333",
        navthumbnavigationstyle:"auto",
        borderradius:0,
        navbuttonhighlightcolor:"#333333",
        textpositionstatic:"bottom",
        navthumbstyle:"imageandtitle",
        textcss:"display:block; padding:12px; text-align:left;",
        navbordercolor:"",
        navpreviewarrowimage:"previewarrow-16-8-0.png",
        showbottomshadow:false,
        backgroundimage:"",
        navposition:"bottom",
        navpreviewarrowwidth:16,
        bottomshadowimagetop:95,
        textpositiondynamic:"bottomleft",
        navshowbuttons:false,
        navthumbtitlecss:"display:block;position:relative;padding:2px 4px;text-align:center;font:bold 11px Arial,Helvetica,sans-serif;color:#333;",
        textpositionmarginbottom:24,
        slice: {
            duration:1500,
            easing:"easeOutCubic",
            checked:true,
            effects:"up,down,updown",
            slicecount:10
        },
        transition:"slice"*/
    });
});